id: opecha:P006939
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25599
  title: ཡི་དམ་ཆོས་སྐྱོང་ཁག་ཅིག་གི་བྱུང་བ་བརྗོད་པ།
  volume:
    008fee7a1c3b4b21ade9c499b96e53dd:
      image_group_id: I1KG25601
      title: Volume 1 of yi dam chos skyong khag cig gi byung ba brjod pa/
      volume_number: 1
      total_pages: 361
  author: ''
ebook_metadata:
  title: ཡི་དམ་ཆོས་སྐྱོང་ཁག་ཅིག་གི་བྱུང་བ་བརྗོད་པ།
  author: ''
  sku: P006939
  cover: cover.jpg
  layers:
  - pagination
