id: P006939
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:31:51.737738
source_metadata:
  id: bdr:W1KG25599
  title: ཡི་དམ་ཆོས་སྐྱོང་ཁག་ཅིག་གི་བྱུང་བ་བརྗོད་པ།
  author: ''
  volumes:
    008fee7a1c3b4b21ade9c499b96e53dd:
      image_group_id: I1KG25601
      title: Volume 1 of yi dam chos skyong khag cig gi byung ba brjod pa/
      volume_number: 1
      total_pages: 361
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
