id: P006939
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25599
  title: ཡི་དམ་ཆོས་སྐྱོང་ཁག་ཅིག་གི་བྱུང་བ་བརྗོད་པ།
  author: ''
  volumes:
    7efcac5ef0cd45ddb043470fa5b1f34c:
      image_group_id: I1KG25601
      title: ''
      volume_number: 1
      total_pages: 361
ebook_metadata:
  title: ཡི་དམ་ཆོས་སྐྱོང་ཁག་ཅིག་གི་བྱུང་བ་བརྗོད་པ།
  author: ''
  sku: P006939
  cover: cover.jpg
  layers:
  - pagination
